networks:
  itmo:

services:
  front:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8090:80"
    networks:
      - itmo


  backend:
    build:
      context: ./back
    networks:
      - itmo

